version: '3.8'

services:
  app:
    image: php:8.3-fpm-alpine
    container_name: geo-contacts-app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - geo-contacts-net

  nginx:
    image: nginx:stable-alpine
    container_name: geo-contacts-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - geo-contacts-net

  db:
    image: mysql:8.0
    container_name: geo-contacts-db
    restart: always
    environment:
      MYSQL_DATABASE: geo_contacts
      MYSQL_USER: application
      MYSQL_PASSWORD: application
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - geo-contacts-net

  node:
    image: node:20-alpine
    container_name: geo-contacts-node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - geo-contacts-net

volumes:
  dbdata:

networks:
  geo-contacts-net:
