name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate composer.json
        run: composer validate
        working-directory: ./backend

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: ./backend

      - name: Run Pint
        run: ./vendor/bin/pint --test
        working-directory: ./backend
        continue-on-error: true

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
        working-directory: ./backend
        continue-on-error: true
